obstacle_range: 3.0
raytrace_range: 3.5

#footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
footprint: [[0.375, -0.34], [0.375, 0.34], [-0.375,0.34], [-0.375, -0.34]]

inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: robot_front_laser_base_link, data_type: LaserScan, topic: robot/front_laser/scan, marking: true, clearing: true}
