global_costmap:
  global_frame: $(arg global_frame)
  robot_base_frame: $(arg base_frame)

  #update_frequency: 10.0
  update_frequency: 5.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: true
